export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const TOGGLE_LIVE_SESSION = "TOGGLE_LIVE_SESSION";
export const CREATE_ROOM = "CREATE_ROOM";
export const GUEST_JOINED_ROOM = "GUEST_JOINED_ROOM";

export const CHANGE_SLIDER = "CHANGE_SLIDER";
