export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const CREATE_ROOM = "CREATE_ROOM";
export const GUEST_JOINED_ROOM = "GUEST_JOINED_ROOM";

export const CHANGE_SLIDER = "CHANGE_SLIDER";
export const SESSION_STARTED = "SESSION_STARTED";
export const SESSION_STOPPED = "SESSION_STOPPED";
export const SESSION_DETAILS = "SESSION_DETAILS";
export const SET_SESSION_AVERAGE = "SET_SESSION_AVERAGE";
export const VOTING_INPUT = "VOTING_INPUT";
export const CANCEL_SESSION = "CANCEL_SESSION";
